### ISSUE TITLE
Keep up the good work!

### ISSUE THREAD

**Issue by fuzzyweapon** [Aeltumn/Chisels-and-Bits-2#12]
Just wanted to leave some encouragement, and if you do decide to release alphas or betas on curseforge (or even somewhere else), I'd be happy to help out with testing latest stable features along with any interested players on my server (though we'd be unlikely to install anything that is in danger of serious corruption, etc).

**Comment by fuzzyweapon** [comment]
I see you've got releases in the Releases tab.  I'll pull the latest release down and check it out!

**Comment by Aeltumn** [comment]
Thanks! The currently released builds are not quite ready to use (they work but many features are unfinished) but I've been working hard on alpha 3 which will hopefully be actually survival ready. As soon as the builds are both feature complete (and fully usable in survival) I'll start releasing them as betas on curseforge. I originally wanted to release weekly alpha's but there's been so much that I really want to work on at the moment that I haven't had a working build in weeks. (and I've been busy too)
