### ISSUE TITLE
I'm not able to craft a iron chisel!!

### ISSUE THREAD

**Issue by ArantasticYT** [Aeltumn/Chisels-and-Bits-2#15]
I followed the crafting recipe from the website and it does not work!!
![image](https://user-images.githubusercontent.com/58235813/69676634-6246d180-105e-11ea-9fba-e52e349b5e71.png)

**Comment by SanjivanM** [comment]
If I recall correctly, tiered chisels are no longer a thing...

**Comment by Aeltumn** [comment]
> 
> 
> If I recall correctly, tiered chisels are no longer a thing...

As @SanjivanM said, one of the changes in C&B2 is that tiered chisels are no longer a thing. You can only make chisels from gold, but a golden chisel can break every kind of block (even obisidan) and the durability is very high so you won't need to craft multiple chisels as often.

**Comment by vinnyg0621** [comment]
Corrected: I'm not able to craft an iron chisel!!
