### ISSUE TITLE
All chiseled blocks stop rendering and become invisible randomly

### ISSUE THREAD

**Issue by boltyboi** [Aeltumn/Chisels-and-Bits-2#19]
so i was messing around with this mod and all of a sudden, whatever i placed was invisible. If i rejoin the server that I am on however, everything that has been chiseled will become invisible as well! The only way that I have found to fix this is to re-open the game, but I think it would be great if this was fixed, so that I don't need to reopen minecraft everytime i want to make a mini cactus or something.
Thanks for reading,
boltyboi

EDIT: I am not using optifine btw, if that changes anything

**Comment by Aeltumn** [comment]
Thank you for reporting this bug, it's a bug that I have internally also discovered but not put on the public issue list as its cause requires some technical knowledge. I have renamed the thread to a more descriptive title so others that have the same problem know where to look.

Reason for the bug: sometimes the rendering thread can crash which causes all rendering to stop working, I've been researching why the bug happens but haven't been able to fix it.

**Comment by boltyboi** [comment]
Ok then, thanks for clarifying :)

**Comment by Aeltumn** [comment]
Issue should have been solved in the latest version for 1.14.
