### ISSUE TITLE
Porting to 1.15

### ISSUE THREAD

**Issue by Aeltumn** [Aeltumn/Chisels-and-Bits-2#21]
The plan is to port to 1.15 after the first alpha/beta has been released on curseforge. In this way there will be a working version of C&B available for 1.14. Furthermore, the changes in 1.15 are pretty significant and there are some fields/methods that have not been given readable names yet.

So, I'll port to 1.15 after the first public release of C&B and hopefully by that time the Forge guys have had some time to figure things out.

**Comment by vinnyg0621** [comment]
I'm so excited!

**Comment by name-here** [comment]
Exciting that C&B is not dead!  I look forward to an (eventual) full release!

**Comment by Aeltumn** [comment]
Porting to 1.15 has started as of today.
