### ISSUE TITLE
Radial menu can still be opened and used when opening the inventory menu

### ISSUE THREAD

**Issue by MPNanKing** [Aeltumn/Chisels-and-Bits-2#25]
C&B2 alpha4
Game version 1.14.4 , forge 28.1.108

![4](https://user-images.githubusercontent.com/45160221/71549069-4b472680-29f2-11ea-8369-f4bcae57720a.png)

You can still open all the radial menus when you open the inventory menu, and you can also select the function of it , release the 'Alt' , inventory menu and radial menus are all closed.

![5-1](https://user-images.githubusercontent.com/45160221/71549070-4bdfbd00-29f2-11ea-8332-ae86300a9d9e.png)
![mea](https://user-images.githubusercontent.com/45160221/71549276-f86f6e00-29f5-11ea-85d0-2883c00939f1.png)

After opening and closing many times , tape measure menu becomes like this.I do n’t know the specific conditions it becomes like this.

Overlapping menus will only be displayed on the changed tape measure , the new tape measure will not be affected

**Comment by Aeltumn** [comment]
Thanks for reporting this issue, it's been fixed now. It'll be included in alpha 5.
