### ISSUE TITLE
Chiseled blocks display incorrectly when adjacent block be destroyed

### ISSUE THREAD

**Issue by MPNanKing** [Aeltumn/Chisels-and-Bits-2#26]
C&B2 alpha4
Game version 1.14.4 , forge 28.1.108

A block adjacent to chiseled block is destroyed and the chiseled block is displayed incorrectly.

![x](https://user-images.githubusercontent.com/45160221/71549423-ff977b80-29f7-11ea-9874-4eff00be1322.png)
![2](https://user-images.githubusercontent.com/45160221/71549422-fefee500-29f7-11ea-954d-39cb47d1f369.png)

**Comment by Aeltumn** [comment]
This issue will be fixed in alpha 5, this worked properly somewhere during the development of alpha 4 but it broke recently.
