### ISSUE TITLE
Will FlatColoredBlocks be integrated into C&B2 ?

### ISSUE THREAD

**Issue by MPNanKing** [Aeltumn/Chisels-and-Bits-2#28]
I built a lot of things with C&B and FCB, but since there is no higher version of FCB, so ,I think it would be inconvenient to update the world of 1.12 to a higher version.

**Comment by Aeltumn** [comment]
Yes! C&B2 will have an item called the pallette, it can be used to freely select a rgba colour and use that in your builds. I'll also see if I can make it so the WorldFixer (and application I'm writing that converts 1.12 worlds to 1.14 C&B) can update old FCB bits into new coloured bits.

**Comment by vinnyg0621** [comment]
No spaces before question marks
