### ISSUE TITLE
Where can i get the mod?

### ISSUE THREAD

**Issue by Panduso** [Aeltumn/Chisels-and-Bits-2#3]
i searched up on twitch, and i cant find the mod, so where can i get it?

**Comment by Aeltumn** [comment]
Currently the mod is in very early alpha stages and doesn't have a curseforge page yet. When the mod is fully usable (I'm currently also waiting on some forge PR's for it to even work properly) I'll release a working jar here on github but the mod probably won't go up on curseforge until it has at least every feature the original C&B had.

**Comment by Panduso** [comment]
Will you make the mod for 1.12.2 first?

**Comment by Aeltumn** [comment]
No, sorry! This mod is only for 1.14+, if you want to play with C&B2 on 1.12 you should just use the original C&B.
