### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Domsmasher1** [Aeltumn/Chisels-and-Bits-2#30]
When i try run the alpha4 version on my server, my server does not like it and crashes.
heres crash report:
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/14/20 1:48 AM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Chisels & Bits 2 (chiselsandbits2) has failed to load correctly
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.14.138-114.102.amzn2.x86_64
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2089532920 bytes (1992 MB) / 2459959296 bytes (2346 MB) up to 3728736256 bytes (3556 MB)
	CPUs: 2
	JVM Flags: 2 total; -Xmx4000M -Xms2048M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.105.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.105.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.105.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.105.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.105.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.105
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.105-server.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
		forge-1.14.4-28.1.105-universal.jar Forge {forge@28.1.105 CREATE_REGISTRIES}
		simplecoloredblocks-1.2.1.jar Simple Colored Blocks {simplecoloredblocks@1.2.1 CREATE_REGISTRIES}
		chiselsandbits2-alpha4.jar Chisels & Bits 2 {chiselsandbits2@alpha4 ERROR}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Aeltumn** [comment]
This is a known issue and it will be fixed in alpha 5. Thanks for reporting it!
