### ISSUE TITLE
Cant match two blocks with biome colors when Chiseled

### ISSUE THREAD

**Issue by ricey125** [Aeltumn/Chisels-and-Bits-2#31]
Hello, I am using conquest reforged mod along with C&B. Ive noticed that diorite and stone do not retain their swampland color when chiseled while grass and leaves do. I was wondering if there is a simple fix for this?
MC Version: 1.12.2
C&B Version: 14.33
Do You have Optifine: Yes
Conquest Reforged: 3.0.2-mc1.12.2

**Comment by Aeltumn** [comment]
Please keep issues for C&B1 on its own github page.
