### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by FlushDesert22** [Aeltumn/Chisels-and-Bits-2#33]
When ever I try to load a world with the chisel and bit blocks placed, it crashes. I did get this error though: minecraft java.lang.NoClassDefFoundError. If this is a client issue and not an issue with the mod itself, please help me to fix it.

**Comment by Aeltumn** [comment]
This is unfortunately a known issue for 1.14 that's very complicated and a fundamental problem that I'm going to address in the 1.15 version. This issue occurs on ~30% of startups and happens more for some folks than for others.

**Comment by zzzpixelflamezzz** [comment]
I just have a fast PC

**Comment by Aeltumn** [comment]
Hopefully fixed as of Alpha 5.1.
