### ISSUE TITLE
Crash when right clicking bit on floating grass (no block below)

### ISSUE THREAD

**Issue by DeadlyLazy** [Aeltumn/Chisels-and-Bits-2#38]
https://pastebin.com/MZK7CS0J

Above crash report linked, was using a block of diamond bit on a floating tall grass (due to the worldgen water lakes). I'm aware the mod is in alpha but just thought I'd report the bug

**Comment by Aeltumn** [comment]
Thanks for the report! I'm surprised I haven't encountered this bug myself really. This is actually already fixed on the 1.15 version (I changed the code that caused the bug in 1.15 for unrelated reasons) so I'm going to close this, but this certainly is a bug in 1.14.
