### ISSUE TITLE
Game crashing when Shift + Right-Click in the air with any bit in the player's hand

### ISSUE THREAD

**Issue by Tompouce-onGit** [Aeltumn/Chisels-and-Bits-2#39]
I was playing around with the latest snapshot of your mod, on a freshly created creative world.
At some point I saw the tooltip for bits, which said "Sneak + click air to unlock". I wasn't sure what that meant so I tried it, which caused the game to crash.
I tried with other bits as well to see if the crash still occured, and it did. It seams that is happens with any types of bits, though I have only tested a handfew myself.
I saw that #38 reported a similar issue about the game crashing when right-clicking with bits on floating grass, but I figured this was a different issue since it happens with shift+right-click and only when targeting the air as far as I can tell.

I used the recomended version of Forge for mc 1.14.4, which is version 28.2.0.
The only mods listed under the in-game 'mods' screen provided my Forge on the starting menu are:

- Minecraft v1.14.4 deobfuscated by MCP (Minecraft Coder Pack) (Installed automatically by Forge)
- Forge v28.2.0
- Chisel & Bits 2 v0.5.1a

and there are no other files in my mod folder.

Here is the crash report of the first crash:
[crash-2020-05-03_21.35.18-client.txt](https://github.com/Aeltumn/Chisels-and-Bits-2/files/4571467/crash-2020-05-03_21.35.18-client.txt)

**Comment by Aeltumn** [comment]
Thanks for the report! This is an easy fix, I really don't know why I didn't ever get this as an issue whilst developing. If there is another 1.14 alpha this is fixed.
