### ISSUE TITLE
Adding fluid bit placing, need suggestions!

### ISSUE THREAD

**Issue by Aeltumn** [Aeltumn/Chisels-and-Bits-2#4]
Recently the new Fluid system was added into Forge and hopefully soon the ClickInputEvent will finally be added so that I can begin work on finishing all the functionality of the chisel item.

However, as I've described in the README.md the way you place bits has changed in C&B2. The bit item doesn't exist anymore. This creates a problem for fluids.. bit bags store block bits, palettes store coloured bits, but where should we store liquid bits?

*Quick Recap:*
In C&B2 you do all breaking and placing of bits directly from the chisel, you left-click to break a bit and you right-click to place a bit. The most recently selected bit will be placed when you right-click. Bits are now internally one of three types: Block, Colour or Fluid.
Block bits are stored in Bit Bags (and selected in the bit bag's Left Alt/Radial Menu), coloured bits are stored in Palettes (there'll be a RGB colour picker interface where you can bookmark up to 12 colours that can be selected in the Left Alt/Radial Menu) but fluid bits currently don't have a way to get selected/obtained.

Whatever item is going to store liquid bits will probably work in a similar way the bit bag does, it stores liquid bits and allows you to select the one you want. I just don't know how to name/texture the item to make it fit with the aesthetic of the mod, some possibilities:

- "Bit Bucket" -> Just an ordinary bucket, will probably be confusing unless the texture is significantly different from normal buckets.
- "Gravity Well" -> A purple looking "gravity" bucket, the name hints it uses imaginary gravity shenanigans to make the liquids float.
- "Bit Cup" -> A measuring cup.

I'd love to hear some ideas!

**Comment by MysCyanide** [comment]
I like the idea of the "Bit Cup". It makes the item unique and not like anything else currently in minecraft. Maybe the cup could look like a science beaker, rather than a kitchen measuring cup? I just don't think lava belongs in the kitchen 😝

**Comment by Hamuelin** [comment]
To expand on the Bit Cup, a conical flask would probably look pretty spot on. As MysCyanide said, something Science related would work well as it's unlike anything currently in minecraft, and flasks/beakers are going to be a pretty easy design to make, and are visually simple.

**Comment by Aeltumn** [comment]
Going for a conical flask does sound like a cool idea, art isn't my greatest skill so if someone wants to make a texture for it that'd be great. There's quite a bit of time to think about this though, development is a bit quiet right now because I'm waiting on Forge to add one of two PRs which allows proper cancelling of block breaking so I can finish the chisel.

**Comment by fuzzyweapon** [comment]
"Bit Beaker" ??  There are conical beakers (and it could be visually designed to look like a conical flask since they are fairly similar and the conical flask has a stronger silhouette, making it a better candidate for smaller inventory icons).  "Bit Cup" is also cool.  Nice and short, but when I think of a cup I think of a goblet or a cup first, not a scientific flask.

I love "Bit Bucket" but I think it'd be difficult to distinguish from normal buckets and at a glance, people could confuse (when they are going fast).

**Comment by Aeltumn** [comment]
I think I'm going with the Bit Beaker and make it look like a conical beaker. Those conical flasks/beakers are indeed really distinct, and with only 16x16 it's important to give it a good silhouette. I'm really bad at pixel art so if someone can draw a nice looking conical beaker, let me know!

**Comment by SalviaUnga** [comment]
Yes, I agree, conical flask is a very good idea for a Bit Beaker. I'm new at graphic design, but I can try to draw not so bad, not so good pixel art for this. I don't have many experience in pixel art, but i think it will be enough. Hope that I will have enough time for this.

Sorry if my English is bad, I'm Russian.

**Comment by Aeltumn** [comment]
> 
> 
> Yes, I agree, conical flask is a very good idea for a Bit Beaker. I'm new at graphic design, but I can try to draw not so bad, not so good pixel art for this. I don't have many experience in pixel art, but i think it will be enough. Hope that I will have enough time for this.
> 
> Sorry if my English is bad, I'm Russian.

No worries, artwork can get put into the mod whenever someone has the time to make it. The first public releases are still a fair few weeks away so there's no rush.

I'm closing this issue, I've settled on the Bit Beaker.
