### ISSUE TITLE
Having dropped bits on the ground causes a crash

### ISSUE THREAD

**Issue by Tompouce-onGit** [Aeltumn/Chisels-and-Bits-2#40]
Noticed this while playing around with the latest version of the mod on the releases page. When I dropped a bit from my inventory tha game crashed, and every time I try to load the world it crashed right away. (i.e. after the loading is done, I spawn in the world and the game immediately crashes)
Seems to happen with any type of bit, though I have only tested a handfew.

Judging by the message displayed by the launcher after the crash, it seems to be a rendering issue with the dropped items.

I used the recomended version of Forge for mc 1.14.4, which is version 28.2.0.
The only mods listed under the in-game 'mods' screen provided my Forge on the starting menu are:

- Minecraft v1.14.4 deobfuscated by MCP (Minecraft Coder Pack) (Installed automatically by Forge)
- Forge v28.2.0
- Chisel & Bits 2 v0.5.1a

and there are no other files in my mod folder.

Here is the crash report:
[crash-2020-05-03_22.56.58-client.txt](https://github.com/Aeltumn/Chisels-and-Bits-2/files/4571663/crash-2020-05-03_22.56.58-client.txt)

**Comment by Aeltumn** [comment]
I've fixed this, if there is another 1.14 alpha that one will contain the fix. This fix will make you able to load your worlds again.

**Comment by Tompouce-onGit** [comment]
They were just creative worlds meant for the sole purpose of testing the mod, so no harm done.
Thanks for the fix.
