### ISSUE TITLE
How and Where Can I Download 1.15.2

### ISSUE THREAD

**Issue by BazookaSquid12** [Aeltumn/Chisels-and-Bits-2#44]
Just curious where I can get the 1.15.2 version.

**Comment by Aeltumn** [comment]
There isn't a downloadable jar for 1.15.2 yet.

**Comment by vinnyg0621** [comment]
You forgot to put a question mark

**Comment by BazookaSquid12** [comment]
That's pretty irrelevant.

**Comment by vinnyg0621** [comment]
no it's not

**Comment by vinnyg0621** [comment]
you should cause it's better grammar
