### ISSUE TITLE
Dependency still exist for MCMultiPart API ?

### ISSUE THREAD

**Issue by smmmadden** [Aeltumn/Chisels-and-Bits-2#47]
https://www.curseforge.com/minecraft/mc-mods/mcmultipart/files was listed as the dependency for the original C&B.  Does the same apply here and if so, do you have the 1.14 version of it?
Thanks - Steve

**Comment by Aeltumn** [comment]
MC Multipart no longer exists in 1.14+ so it's no longer required. However, if any form of Multipart plugin gets made for 1.14 I'll definitely try to support it.
