### ISSUE TITLE
Bits do not appear when placed but can be interacted with

### ISSUE THREAD

**Issue by SupercarMafia** [Aeltumn/Chisels-and-Bits-2#53]
Hello,

When I started up my new world with Chisels and Bits 2, I attempted to place a bit, but it was completely invisible. But, you could easily interact with it. I attempted to try different bits, but that didn't change anything. I deleted and created a whole new world, but the problem still persisted. I have looked on the issues reported but none of them quite described what I was experiencing. Any help is appreciated. I can provide you with anything you need: error reports, screenshots, etc.

**Comment by Aeltumn** [comment]
Can you send the client/server logs and what version of C&B2 are you using?

**Comment by SupercarMafia** [comment]
I am using C&B2 version 5.2 for 1.14.4 and do you mean the log under the "logs" folder under .minecraft?

**Comment by SupercarMafia** [comment]
Actually, after removing Optifine and WorldEdit from my mods, it appears to work. Is there some sort of non-compatibility between C&B2 and those?

**Comment by SupercarMafia** [comment]
I was using OptiFine_1.14.4_HD_U_F5 and worldedit-forge-mc1.14.4-7.0.1

**Comment by LordMZTE** [comment]
ive had this issue on 1.15 but i didnt report it since the version seemed very unfinished so i thought it was a known issue

**Comment by Aeltumn** [comment]
> ive had this issue on 1.15 but i didnt report it since the version seemed very unfinished so i thought it was a known issue

The 1.15 issue is unrelated, on 1.15 the block rendering isn't finished so they don't show up.

> Actually, after removing Optifine and WorldEdit from my mods, it appears to work. Is there some sort of non-compatibility between C&B2 and those?

Currently C&B2 is incompatible with Optifine.
