### ISSUE TITLE
Do you have a release date for 1.15.2?

### ISSUE THREAD

**Issue by PotatoSocks6** [Aeltumn/Chisels-and-Bits-2#54]
I love chisel and bits and want to thank you SO much for doing this. Do you have a release date in mind for 1.15.2 yet?

**Comment by Aeltumn** [comment]
Not really, I work on the mod whenever I've got time. It'll be done when it's done.

**Comment by Aeltumn** [comment]
The original Chisels & Bits has now been ported to 1.16, I'll continue developing this mod but you can now at least play a C&B.
