### ISSUE TITLE
1.16.1?

### ISSUE THREAD

**Issue by MrScautHD** [Aeltumn/Chisels-and-Bits-2#59]

**Comment by vinnyg0621** [comment]
I'm excited for the 1.15/1.16 update!

**Comment by eksynn** [comment]
hoping for a 1.16.3 release soon! (or just 1.16 in general)

**Comment by Aeltumn** [comment]
The original Chisels & Bits has now been ported to 1.16, I'll continue developing this mod but you can now at least play a C&B.
