### ISSUE TITLE
invisible blocks chisels & bits 2

### ISSUE THREAD

**Issue by Luismi28** [Aeltumn/Chisels-and-Bits-2#60]
at the moment of loading the mod everything is fine but when I place a block of the mod or break some other block using this same mod, it becomes invisible and cannot be built, please help me by solving this error. I attach 3 images because I am a new in this and I do not know how to attach .log files.
![2020-08-07_15 20 53](https://user-images.githubusercontent.com/69366837/89685484-0f4a3d00-d8c2-11ea-98ed-c39403d114bb.png)
![2020-08-07_15 20 54](https://user-images.githubusercontent.com/69366837/89685593-428ccc00-d8c2-11ea-967d-c99a084a116a.png)

![2020-08-07_15 20 43](https://user-images.githubusercontent.com/69366837/89685379-dc07ae00-d8c1-11ea-8109-dcf28c8e7d23.png)
@Aeltumn since you are developing this mod for version 1.14.4 please help me.
P. S: i don't speak english, i'm using google translator to query them for this error.

**Comment by Aeltumn** [comment]
The mod is currently not compatible with Optifine unfortunately.

**Comment by Luismi28** [comment]
> Desafortunadamente, el mod actualmente no es compatible con Optifine.

when will it be possible to solve this?
since I remember that in the original mod if it was compatible

**Comment by Aeltumn** [comment]
> 
> 
> > Desafortunadamente, el mod actualmente no es compatible con Optifine.
> 
> when will it be possible to solve this?
> since I remember that in the original mod if it was compatible
I'm trying to support Optifine, but unfortunately Optifine has no documentation so it's quite hard to make it work as I can find no information on why it isn't working.
I'm trying to fully support Optifine in the 1.15+ version of C&B2.

**Comment by Luismi28** [comment]
In the version for 1.15+ are you going to add the crystals and leaves? Because in this version of 1.14.4 of C & B2 there are no crystals or leaves to make mini trees or details with the glasses
