### ISSUE TITLE
chiseling a block cause game to crash

### ISSUE THREAD

**Issue by Alexopfpz** [Aeltumn/Chisels-and-Bits-2#62]
I left-clicked a stone block with a stone bit to chisel it and my game crashed.

**Comment by NurioHin** [comment]
I'll ask this because I know this question will come. Can you post the crash log?

**Comment by Alexopfpz** [comment]
I will post it as soon as I can but I am not on the pc at the moment. Do
you want me to send it to you by email or to post it on github? I am new
there so I don't know exactly how it works sorry

Il giorno lun 10 ago 2020 alle 15:35 NurioHin <notifications@github.com> ha
scritto:

**Comment by Aeltumn** [comment]
You can either upload the log file directly or post it through a website like https://hastebin.com/ but you should post it here on GitHub.

**Comment by Aeltumn** [comment]
Going to close as there is no crash report so no way to fix the issue.
