### ISSUE TITLE
Pls add 1.15 version

### ISSUE THREAD

**Issue by Crypto-cry** [Aeltumn/Chisels-and-Bits-2#63]
Rlly i want this mod for 1.15  and i want to say Ty for the mod but please release the mod to 1.15

**Comment by LordMZTE** [comment]
why not just build it yourself? (also, its really not ready to be played with in 1.15 yet ;D)

**Comment by Crypto-cry** [comment]
Thats a good point

**Comment by Aeltumn** [comment]
There's still lots of work that needs to be done to make the 1.15 version work, but I'm busy with other projects at the moment. I'll release it when it's done but I can't make any promises on when that will be.
