### ISSUE TITLE
Any news on a 1.16.3 release?

### ISSUE THREAD

**Issue by eksynn** [Aeltumn/Chisels-and-Bits-2#68]
or just 1.16 in general. (should still work with 1.16.3 right?)

**Comment by Aeltumn** [comment]
I'm still very busy and unable to spend a lot of time on C&B2, but someone else is working on a 1.16 port of C&B that may be done soon:tm:.

**Comment by Aeltumn** [comment]
The original Chisels & Bits has now been ported to 1.16, I'll continue developing this mod but you can now at least play a C&B.
