### ISSUE TITLE
Need feedback: Recipes for the new items!

### ISSUE THREAD

**Issue by Aeltumn** [Aeltumn/Chisels-and-Bits-2#7]
I've got another issue that I'd like some feedback on! What should the recipes be for the new items?

So, let's address all of the (new) items: (ignoring Chisel, Saw, Tape Measure and Bit Bag, those are already perfect)
* Pattern: I think the recipe is pretty good right now. The black dye is always black, the other dyes can be any colour.
![image](https://user-images.githubusercontent.com/12281102/65060109-92e00000-d977-11e9-9cdd-9b3a2d6c61e8.png)
* Wrench: This recipe _could_ be better.
-- Already has a new good recipe! --
* Bit Beaker: I don't like this one. Glass panes/glass can be any colour, not just blue/gray.
-- Already has a new good recipe! --
* Mallet: I couldn't think of anything creative for this one.
-- Already has a new good recipe! --
* Blueprint: Also not great. Similar to the pattern.
![image](https://user-images.githubusercontent.com/12281102/65060349-f9fdb480-d977-11e9-803a-5f9a58b4d31a.png)
* Palette: This one is decent I think, the dyes can be any colour.
-- Already has a new good recipe! --

General note on which items I've currently used in the recipes, I've mostly used the tags with everything, so if it's a log every type of log is allowed. If it's glass then all (stained) glass is allowed.
Also note that the textures for the palette and bit beaker are both my beautiful placeholder images.

**Comment by SalviaUnga** [comment]
I have some ideas for the crafting recipes, but I'm not at home yet.

**Comment by SalviaUnga** [comment]
**Pattern:** _Recipe is looking very good right now, so better don't change it._

**Wrench:** _This recipe could be better. Instead of two sticks and two planks it is better to make one stick and plank._
![image](https://user-images.githubusercontent.com/43315029/65415942-f60ede00-de20-11e9-9226-2755a7a84de7.png)

**Bit Beaker:** _This recipe is too costly. Better to use a bit in the center and four glass panes around it._
![image](https://user-images.githubusercontent.com/43315029/65416110-556cee00-de21-11e9-9687-de3d6c581925.png)

**Mallet:** _Will be better to use one stick and one log._
![image](https://user-images.githubusercontent.com/43315029/65416214-949b3f00-de21-11e9-820d-04951a26e1a4.png)

**Blueprint:** _I couldn't think of anything more creative than black dye and three patterns around it._
![image](https://user-images.githubusercontent.com/43315029/65416399-e80d8d00-de21-11e9-8ae3-01edb5619433.png)

**Palette:** _This recipe is good, but for another variant, you can replace the iron for wooden slab._
![image](https://user-images.githubusercontent.com/43315029/65416508-36bb2700-de22-11e9-8b11-fbf08a1df57d.png)

Good luck! Your mod will be great.

**Comment by Aeltumn** [comment]
> 
> 
> **Pattern:** _Recipe is looking very good right now, so better don't change it._
> 
> **Wrench:** _This recipe could be better. Instead of two sticks and two planks it is better to make one stick and plank._
> 
> **Bit Beaker:** _This recipe is too costly. Better to use a bit in the center and four glass panes around it._
> 
> **Mallet:** _Will be better to use one stick and one log._
> 
> **Blueprint:** _I couldn't think of anything more creative than black dye and three patterns around it._
> 
> **Palette:** _This recipe is good, but for another variant, you can replace the iron for wooden slab._
> 
> Good luck! Your mod will be great.

Wrench / Mallet -> I think having these as a stick and one wood would conflict with other mods too easily. These recipes can also be a bit more bigger (look complicated) as they are both items you don't need often.

Blueprint -> That's a decent recipe. It fits that the blueprint texture looks like three patterns.

Palette -> The iron ingot was mostly to make it similar to the texture which had an metallic look. If the final texture has a more wooden look I'll definitely make it a slab.

Beaker -> Maybe a bucket in the middle? Bit items don't exist anymore actually.. (I wrote about it in the README)

**Comment by kelle1** [comment]
I hope that it isn't too late to add to this, as I have a couple ideas for a few of these items.

The **Wrench**: There are 2 suggestions I have, a wooden wrench, like the one in you post, or possibly a metal wrench, as they more commonly are in the real world.

Wooden design:
![image](https://user-images.githubusercontent.com/44987764/66710259-0844c200-edb8-11e9-953d-ba8bc008fd42.png)

Metal design:
![image](https://user-images.githubusercontent.com/44987764/66710266-21e60980-edb8-11e9-9478-5a473cfecb5c.png)

The **Mallet**: Same as above, maybe a wooden design or a metal design.

Wooden design:
![image](https://user-images.githubusercontent.com/44987764/66710275-5659c580-edb8-11e9-8d51-7f4eae2b35ba.png)

Metal design:
![image](https://user-images.githubusercontent.com/44987764/66710281-6a9dc280-edb8-11e9-9e81-77b92ec589f7.png)

In my opinion, I believe that the metal designs are better, but if you use these or not its up to you. 

I also want to say, thank you for continuing on this project. I will be definitely using this mod on release.

**Comment by Aeltumn** [comment]
> 
> 
> I hope that it isn't too late to add to this, as I have a couple ideas for a few of these items.
> 
> The **Wrench**: There are 2 suggestions I have, a wooden wrench, like the one in your post, or possibly a metal wrench, as they more commonly are in the real world.
> 
> Wooden design:
> ![image](https://user-images.githubusercontent.com/44987764/66710259-0844c200-edb8-11e9-953d-ba8bc008fd42.png)
> 
> Metal design:
> ![image](https://user-images.githubusercontent.com/44987764/66710266-21e60980-edb8-11e9-9478-5a473cfecb5c.png)
> 
> The **Mallet**: Same as above, maybe a wooden design or a metal design.
> 
> Wooden design:
> ![image](https://user-images.githubusercontent.com/44987764/66710275-5659c580-edb8-11e9-8d51-7f4eae2b35ba.png)
> 
> Metal design:
> ![image](https://user-images.githubusercontent.com/44987764/66710281-6a9dc280-edb8-11e9-9e81-77b92ec589f7.png)
> 
> In my opinion, I believe that the metal designs are better, but if you use these or not its up to you.
> 
> I also want to say, thank you for continuing on this project. I will be definitely using this mod on release.

Thanks for your suggestions, I agree that metal mallets and hammers might be better. Whether I can make them metal depends on the texture. I'm currently using textures from the original mod and the two new ones I've made don't look all too good. If I can find someone who's good at making textures then I'll probably make them metal/iron.

**Comment by kelle1** [comment]
Well, I am not great with creating textures, but here might be a couple ideas for the metal tools. I just substituted the Iron Ingot colours with the colours on their respective parts in the original wooden textures. Hope you like them.

**Wrench**:
![Iron Wrench](https://user-images.githubusercontent.com/44987764/66724115-3502e300-ee65-11e9-8ea5-03ca35f2f265.PNG)

**Mallet**:
![Iron Mallet](https://user-images.githubusercontent.com/44987764/66724116-36cca680-ee65-11e9-89b1-f661f0f77e95.PNG)

**Comment by Aeltumn** [comment]
> 
> 
> Well, I am not great with creating textures, but here might be a couple ideas for the metal tools. I just substituted the Iron Ingot colours with the colours on their respective parts in the original wooden textures. Hope you like them.
> 
> **Wrench**:
> ![Iron Wrench]
> 
> **Mallet**:
> ![Iron Mallet]

Those look pretty good! You can PR them into the mod or send the image files and I'll add them.

**Comment by kelle1** [comment]
I am a little unsure as to exactly what you want, as I am new to this kind of thing, and apologise if this isn't what you want, but this is what I believe you are asking for.
![Iron Wrench](https://user-images.githubusercontent.com/44987764/66744537-1847c900-eec0-11e9-93dc-094c3755af40.png)
![Iron Mallet](https://user-images.githubusercontent.com/44987764/66744543-1aaa2300-eec0-11e9-91a0-7d0f031ddd5b.png)
(These are 16x16 pixel .png files, with blank backgrounds, I believe that is all I have to do with the textures to make them)

**Comment by Aeltumn** [comment]
No worries, what I meant with "you can PR them in" is that you could've made a PR or Pull Request. PR's are a way of contributing code to the mod directly. Sending them like this is fine too, I can now download them and put them into the mod.

**Comment by Aeltumn** [comment]
I think all recipes are decent now, I'll open another issue soon for some community feedback on a general visual design of all the textures.
