### ISSUE TITLE
1.16(.3) port?

### ISSUE THREAD

**Issue by vinnyg0621** [Aeltumn/Chisels-and-Bits-2#71]
can you port this mod to 1.16.3 if there's time?

**Comment by Aeltumn** [comment]
Recently Orion actually ported the original C&B to 1.16.3, it's available on C&B's CF, you'll have to go to files though as it's still a beta release. This is a direct port of the 1.12 C&B so hopefully it'll give you the mod you're looking for.
I'll continue working on C&B2 at a future point and it'll be probably 1.16 (or 1.17), but I don't know yet.

**Comment by vinnyg0621** [comment]
it said it's for 1.16.1. I don't see any 1.16.3 versions on there. it's also saying the mod didn't load cuz it's for 1.16.1

**Comment by Aeltumn** [comment]
The 1.16.3 version just released, you do need to look for it in the files.

**Comment by vinnyg0621** [comment]
oh! I see that it's for 1.16.3! thanks so much! :D
