### ISSUE TITLE
Alpha Version Roadmap

### ISSUE THREAD

**Issue by Aeltumn** [Aeltumn/Chisels-and-Bits-2#9]
Hi there,

I've worked on some other projects for the past two weeks but now it's time to get some more work done on C&B2! The mod is currently "functional" for use in creative mode (the most important part, the chiselled blocks, are working) as all features/items are implemented but many of them lack their full functionality. There are also still lots of bugs and things to take a look at, I've got plenty of experience coding in Java but rendering is new to me and C&B is far more complicated than I expected and it takes a long time for me to really understand it so I can make improvements that don't have unintentional side effects.

_I'm planning on releasing an alpha version after all critical bugs have been taken care of, it won't be on Curse Forge and it'll likely not be fully functional for survival mode. The alpha version will be released through GitHub. I'm hoping to get this alpha out this month with more alpha's in the weeks after with more features and functionality. I'd like to get a beta ready for Curse Forge near the end of this year. (my three requirements for a beta are that the mod is fully usable in survival, has all features C&B1 had and that there are no obvious large bugs anymore)_

Here's the list of features that still need to be added before the first alpha:
- ~~Bit Storage item functionality, currently the chisel places infinite diamond blocks for testing purposes, it should place blocks from the contents of bit bags or beakers.~~
- ~~Rendering fluids and coloured bits~~
- ~~Partial Bit Bag, Bit Beaker and Palette functionality~~
-  ~~Blocks destroying themselves if empty.~~

And there's some critical bugs that need to be fixed:
- ~~When a chunk gets re-rendered it becomes invisible for a few frames.~~
- ~~Chiselled block faces are incorrectly hidden behind neighbouring transparent blocks.~~
- ~~Sporadically when a chunk fails to render it stays invisible until updated.~~
- Placing/breaking normal blocks doesn't trigger chiselled blocks to get updated causing visual glitches.
- Fluids don't render properly next to other fluids.
- Fluids don't look like fluids from the inside.
- Fluids in chiseled blocks don't act like fluids, you can't swim in them, etc.
- Transparent chiseled blocks get less and less transparent the more chiseled blocks are inside the chunk.
- Game crashes when a chiseled block is held in the inventory.
- ~~Coloured bits crash the client when they are rendered. (they're invisible if you manage to not crash)~~
- ~~When a block is first converted into a chiseled block it goes invisible for a few frames.~~

Performance is likely awful in early alpha builds but I'm working hard to understand how C&B1 is coded and why it was coded the way it is so I can make meaningful improvements to areas that can still be optimized.

Thanks for the support, I really hope I can do the original C&B justice.

**Comment by SalviaUnga** [comment]
Good luck in coding! I hope you will do this.

**Comment by Aeltumn** [comment]
First alpha is dropping very soon, so this roadmap has ended.
